# Generated by Django 4.0.1 on 2022-08-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskdetails_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_task_details', to='tasks.task'),
        ),
    ]
