# Generated by Django 4.0.1 on 2022-08-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskdetails_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetails',
            name='modify_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
